#! /usr/bin/env bash

set -e

# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

function install_brew() {
    which brew &>/dev/null || ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew tap Homebrew/bundle
    brew bundle --file=$DIR/Brewfile
    local brew_bash="$(brew --prefix)/bin/bash"
    if ! grep -q ${brew_bash} /etc/shells; then
        sudo bash -c "echo $brew_bash >> /etc/shells"
    fi
    if ! which bash | grep -q ${brew_bash}; then
        sudo chsh -s "$brew_bash" ${USER}
    fi
    brew cleanup
    brew cask cleanup
    brew doctor
}

mkdir -p $HOME/bin
find ${DIR} -name '.[^.DS_Store]*' -type f -depth 1 | xargs -I % ln -sfv % $HOME
mkdir -p $HOME/.ssh
ln -sfv ${DIR}/.ssh/config $HOME/.ssh/config
ln -sfv ${DIR}/default-gems $(rbenv root)/default-gems

install_brew

chmod 0400 $HOME/Dropbox/creds/.ssh/id_rsa
ln -sfv $HOME/Dropbox/creds/.ssh/id_rsa $HOME/.ssh/id_rsa
ln -sfv $HOME/Dropbox/.bash_history $HOME/.bash_history

(docker-machine ls | grep -q default) || docker-machine create default --driver virtualbox

docker-machine-nfs default

RUBY_VERSION="2.4.1"
if ! rbenv versions --bare | grep -q ${RUBY_VERSION}; then
    rbenv install ${RUBY_VERSION} --keep
fi

gem update --system
gem update
gem cleanup

pip install --upgrade pip setuptools glances bottle
