#! /usr/bin/env bash
set -e

function git_sync() {
  local repo="$1"
  local dir="$2"
  if [[ -d $dir ]]; then
    (cd $dir && git pull)
  else
    mkdir -p $dir
    git clone $repo $dir
  fi
}

function install_brew() {
  which brew &> /dev/null || ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  brew bundle
  local brew_bash="`brew --prefix`/bin/bash"
  if ! grep -q $brew_bash /etc/shells; then
    sudo bash -c "echo $brew_bash >> /etc/shells"
  fi
  if ! which bash | grep -q $brew_bash; then
    sudo chsh -s "$brew_bash" $USER
  fi
}

function install_rbenv() {
  local rbenv_root=$HOME/.rbenv
  git_sync "https://github.com/sstephenson/rbenv/" $rbenv_root
  local rbenv_plugins=$rbenv_root/plugins
  git_sync "https://github.com/sstephenson/ruby-build/" $rbenv_plugins/ruby-build
  git_sync "https://github.com/sstephenson/rbenv-gem-rehash/" $rbenv_plugins/rbenv-gem-rehash
}

function setup_vim() {
  mkdir -p $HOME/.vim
  git_sync "https://github.com/gmarik/Vundle.vim.git" $HOME/.vim/bundle/Vundle.vim
  (vim +PluginInstall +qall &> /dev/null) &
}

mkdir -p $HOME/bin
find $PWD -name '.[^.DS_Store]*' -type f -depth 1 | xargs -I % ln -sfv % $HOME
ln -sfv $PWD/.cabal/* $HOME/.cabal

setup_vim
if [[ -z "$NOBREW" ]]; then
  install_brew
fi
if [[ -z "$NORBENV" ]]; then
  install_rbenv
fi

echo 'Bootstrap complete'
