#! /usr/bin/env bash

set -e

brew update
brew upgrade
brew linkapps
brew tap homebrew/binary
brew tap homebrew/completions
brew tap homebrew/dupes
brew tap homebrew/versions

# gnu toolchain
brew install coreutils
brew install binutils
brew install diffutils
brew install ed
brew install findutils
brew install gawk
brew install gnu-indent
brew install gnu-sed
brew install gnu-tar
brew install gnu-which
brew install gnutls
brew install grep
brew install gzip
brew install watch
brew install wdiff
brew install wget
brew install emacs
brew install gpatch
brew install m4
brew install make
brew install bash
brew install gcc
# end gnu toolchain

brew install file-formula
brew install less
brew install python --with-brewed-openssl
brew install rsync
brew install svn
brew install unzip

brew install vim --override-system-vi
brew install tmux
brew install axel
brew install bash-completion
brew install chromedriver
brew install curl
brew install openssl
brew install git --with-blk-sha1 --with-pcre --with-brewed-curl --with-brewed-openssl
brew install tig
brew install maven
brew install node
brew install phantomjs
brew install postgresql
brew install cloc
brew install unrar
brew install ant
brew install sqlite
brew install go
brew install direnv
brew install pstree
brew install tree
brew install youtube-dl
brew install ctags
brew install watch
brew install ack
brew cleanup
brew doctor
