#! /usr/bin/env bash

# set -e

brew update
brew upgrade --all
brew linkapps
brew tap homebrew/binary
brew tap homebrew/completions
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap caskroom/cask


brew install ant
brew install aria2
brew install bash
brew install bash-completion
brew install ctags
brew install curl
brew install direnv
brew install gcc
brew install git --with-blk-sha1 --with-pcre --with-brewed-curl --with-brewed-openssl
brew install hg
brew install go
brew install maven
brew install gradle
brew install openssl
brew install postgresql
brew install pstree
brew install sqlite
brew install tig
brew install tmux
brew install tree
brew install unrar
brew install vim --override-system-vi
brew install jq
brew install awscli
brew install libxml2
brew install libxslt
brew install nmap
brew install mtr
brew install ansible
brew install graphviz
brew install nodejs
brew install packer
brew install docker-completion
brew install docker-compose-completion
brew install leiningen

brew cask install dropbox
brew cask install intellij-idea
brew cask install google-chrome
brew cask install google-drive
brew cask install java
brew install groovy
brew cask install dropbox
brew cask install iterm2
brew cask install keepingyouawake
brew cask install spectacle
brew cask install appcleaner
brew cask install slack
brew cask install steam
brew cask install vagrant
brew cask install firefox
brew cask install chefdk
brew cask install emacs

brew cleanup
brew cask cleanup
brew doctor
