#! /usr/bin/env bash

set -e

brew update
brew upgrade
brew linkapps
brew tap homebrew/binary
brew tap homebrew/completions
brew tap homebrew/dupes
brew tap homebrew/versions


brew install ant
brew install axel
brew install bash
brew install bash-completion
brew install chromedriver
brew install cmake
brew install cloc
brew install cppcheck
brew install cscope
brew install ctags
brew install curl
brew install direnv
brew install gcc
brew install git --with-blk-sha1 --with-pcre --with-brewed-curl --with-brewed-openssl
brew install go
brew install maven
brew install node
brew install openssl
brew install phantomjs
brew install postgresql
brew install pstree
brew install splint
brew install sqlite
brew install tig
brew install tmux
brew install tree
brew install unrar
brew install vim --override-system-vi
brew install ack
brew install leiningen
brew install emacs

brew cleanup
brew doctor
